export const ADD_TODO_LIST = "ADD_TODO_LIST";
export const DELETE_TODO_LIST = "DELETE_TODO_LIST";
export const UPDATE_TODO_TITLE = "UPDATE_TODO_TITLE";
export const DELETE_ALL_TODO_LIST = "DELETE_ALL_TODO_LIST";

export const ADD_TASK = "ADD_TASK";
export const UPDATE_TASK = "UPDATE_TASK";
export const DELETE_TASK = "DELETE_TASK";

export const TOGGLE_TASK_STATUS = "TOGGLE_TASK_STATUS";
